project_id    = "exemplary-point-412614"
region        = "us-east1"
application   = "gke"
ip_cidr_range = "11.0.0.0/16"
gke_num_nodes = "2"
gke_version   = "1.27."
machine_type  = "e2-medium"
node_disk_size = "20"